apiVersion: apps/v1
kind: Deployment
metadata:
  name: proekt_kiii-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: optimusdame/proekt_kiii-app:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: proekt_kiii-app-configmap