apiVersion: v1
kind: PersistentVolume
metadata:
    name: proekt_kiii-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/proekt_kiii