---
apiVersion: v1
kind: Namespace
metadata:
  name: proekt-kiii
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: proekt-kiii-pv
  namespace: proekt-kiii
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/proekt-kiii
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proekt-kiii-pvc
  namespace: proekt-kiii
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proekt-kiii-db-configmap
  namespace: proekt-kiii
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"
  POSTGRES_DB: "proekt-kiii-db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proekt-kiii-app-configmap
  namespace: proekt-kiii
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://proekt-kiii-db-svc:5432/proekt-kiii-db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: proekt-kiii-db-svc
  namespace: proekt-kiii
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30002
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: proekt-kiii-app-svc
  namespace: proekt-kiii
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proekt-kiii-db-deployment
  namespace: proekt-kiii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: proekt-kiii-db-configmap
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: proekt-kiii-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proekt-kiii-app-deployment
  namespace: proekt-kiii
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: optimusdame/proekt-kiii-app:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: proekt-kiii-app-configmap