apiVersion: v1
kind: PersistentVolume
metadata:
  name: proekt-kiii-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/proekt-kiii

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proekt-kiii-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proekt-kiii-db-configmap
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "12345"
  POSTGRES_DB: "proekt-kiii-db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proekt-kiii-configmap
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://proekt-kiii-db-svc:5432/proekt-kiii-db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "12345"

---
apiVersion: v1
kind: Service
metadata:
  name: proekt-kiii-db-svc
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: proekt-kiiiv1-svc
spec:
  clusterIP: None
  selector:
    app: webappv1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: proekt-kiiiv2-svc
spec:
  clusterIP: None
  selector:
    app: webappv2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proekt-kiii-db-statefulset
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: proekt-kiii-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: proekt-kiii-db-configmap
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: proekt-kiii-pvc

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proekt-kiiiv1-statefulset
spec:
  selector:
    matchLabels:
      app: webappv1
  serviceName: proekt-kiiiv1-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: webappv1
    spec:
      containers:
        - name: webappv1-container
          image: optimusdame/proekt-kiii:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: proekt-kiii-configmap

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proekt-kiiiv2-statefulset
spec:
  selector:
    matchLabels:
      app: webappv2
  serviceName: proekt-kiiiv2-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: webappv2
    spec:
      containers:
        - name: webappv2-container
          image: optimusdame/proekt-kiii:2.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: proekt-kiii-configmap